version: "3.8"

services:
  web:
    build:
      context: .
      target: build
    environment:
      VITE_SERVER_URL: ${VITE_SERVER_URL}
      VITE_OPENWEATHER_KEY: ${VITE_OPENWEATHER_KEY}
      VITE_OPENWEATHER_URL: ${VITE_OPENWEATHER_URL}
      VITE_FIREBASE_API_KEY: ${VITE_FIREBASE_API_KEY}
      VITE_FIREBASE_AUTH_DOMAIN: ${VITE_FIREBASE_AUTH_DOMAIN}
      VITE_FIREBASE_PROJECT_ID: ${VITE_FIREBASE_PROJECT_ID}
      VITE_FIREBASE_STORAGE_BUCKET: ${VITE_FIREBASE_STORAGE_BUCKET}
      VITE_FIREBASE_MESSAGING_SENDER_ID: ${VITE_FIREBASE_MESSAGING_SENDER_ID}
      VITE_FIREBASE_APP_ID: ${VITE_FIREBASE_APP_ID}
      VITE_GOOGLE_MAPS_KEY: ${VITE_GOOGLE_MAPS_KEY}

    ports:
      - 5173:5173
    command: bun run dev
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
