name: CICD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image
        run: docker build -t jekku123/countries-app --build-arg VITE_NODE_ENV='production' .
      - name: Publish image to docker hub
        run: docker push jekku123/countries-app:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from docker hub
        run: docker pull jekku123/countries-app:latest
      - name: Delete Old Container
        run: docker rm -f countries-app-container
      - name: Run docker container
        run: docker run -d -p 5173:80 --name countries-app-container \
          -e VITE_OPENWEATHER_KEY=${{ secrets.VITE_OPENWEATHER_KEY }} \
          -e VITE_OPENWEATHER_URL=${{ secrets.VITE_OPENWEATHER_URL }} \
          -e VITE_FIREBASE_API_KEY=${{ secrets.VITE_FIREBASE_API_KEY }} \
          -e VITE_FIREBASE_AUTH_DOMAIN=${{ secrets.VITE_FIREBASE_AUTH_DOMAIN }} \
          -e VITE_FIREBASE_PROJECT_ID=${{ secrets.VITE_FIREBASE_PROJECT_ID }} \
          -e VITE_FIREBASE_STORAGE_BUCKET=${{ secrets.VITE_FIREBASE_STORAGE_BUCKET }} \
          -e VITE_FIREBASE_MESSAGING_SENDER_ID=${{ secrets.VITE_FIREBASE_MESSAGING_SENDER_ID }} \
          -e VITE_FIREBASE_APP_ID=${{ secrets.VITE_FIREBASE_APP_ID }} \
          -e VITE_GOOGLE_MAPS_KEY=${{ secrets.VITE_GOOGLE_MAPS_KEY }} \
          jekku123/countries-app
